// Optimized ComponentResult.tsx
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Download, Copy, Eye, Package, Ruler, Zap, Boxes, Info, Gauge, DollarSign, Move, Gauge as GaugeIcon, Hammer, Battery, Wrench } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useState, useMemo, memo } from "react";
import Component3DView from "./Component3DView";

interface ComponentResultProps {
  data: any;
}

const getComplexityValue = (complexity: string) => {
  const level = complexity?.toLowerCase() || '';
  if (level.includes('low')) return 33;
  if (level.includes('medium')) return 66;
  if (level.includes('high')) return 100;
  return 50;
};

const getCostValue = (cost: string) => {
  const match = cost?.match(/\$?(\d+)/);
  if (match) {
    const value = parseInt(match[1]);
    return Math.min((value / 2000) * 100, 100);
  }
  return 50;
};

const ComponentResult = ({ data }: ComponentResultProps) => {
  const { toast } = useToast();
  const [show3D, setShow3D] = useState(false);

  const complexityValue = useMemo(() => getComplexityValue(data.assembly_complexity), [data.assembly_complexity]);
  const costValue = useMemo(() => getCostValue(data.estimated_cost), [data.estimated_cost]);

  const handleCopy = () => {
    navigator.clipboard.writeText(JSON.stringify(data, null, 2));
    toast({ title: "Copied to Clipboard", description: "Component specifications copied as JSON" });
  };

  const handleDownload = () => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `obasi-ai-${data.component_name.toLowerCase().replace(/\s+/g, "-")}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Downloaded", description: "Saved as JSON" });
  };

  // Helper to render key-value pairs (handles nested objects)
  const renderKeyValuePairs = (obj: Record<string, any>) => {
    return Object.entries(obj || {}).flatMap(([key, value]) => {
      if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
        return Object.entries(value).map(([subKey, subVal]) => (
          <div key={`${key}-${subKey}`} className="flex justify-between py-1 border-b border-muted last:border-0">
            <span className="text-muted-foreground capitalize">{subKey.replace(/_/g, ' ')}:</span>
            <span className="font-medium">{String(subVal)}</span>
          </div>
        ));
      }
      return (
        <div key={key} className="flex justify-between py-1 border-b border-muted last:border-0">
          <span className="text-muted-foreground capitalize">{key.replace(/_/g, ' ')}:</span>
          <span className="font-medium">{String(value)}</span>
        </div>
      );
    });
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <Card className="p-4 md:p-8 shadow-glow border-2 backdrop-blur-sm bg-card/95 transition-all duration-300 hover:shadow-xl">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between mb-8 pb-6 border-b gap-6">
          <div className="flex-1 space-y-3">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-primary/10">
                <Package className="h-7 w-7 text-primary" />
              </div>
              <div>
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Generated by</p>
                <h2 className="text-3xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">MechOne</h2>
                <h4 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">powered by OBASITECH</h4>
              </div>
            </div>
            <div className="space-y-2">
              <p className="text-2xl font-bold">{data.component_name}</p>
              <Badge variant="secondary" className="text-sm px-3 py-1">
                {data.component_type}
              </Badge>
            </div>
          </div>

          <div className="flex flex-wrap gap-2">
            <Button onClick={() => setShow3D(!show3D)} variant="outline">
              <Eye className="mr-2 h-4 w-4" />
              {show3D ? "Hide" : "Show"} 3D View
            </Button>
            <Button onClick={handleCopy} variant="outline">
              <Copy className="mr-2 h-4 w-4" /> Copy
            </Button>
            <Button onClick={handleDownload} variant="outline">
              <Download className="mr-2 h-4 w-4" /> Export
            </Button>
          </div>
        </div>

        {show3D && (
          <div className="mb-8 -mx-4 md:-mx-8">
            <Component3DView specifications={data} />
          </div>
        )}

        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 mb-6">
            <TabsTrigger value="overview"><Info className="mr-2 h-4 w-4" />Overview</TabsTrigger>
            <TabsTrigger value="specs"><Ruler className="mr-2 h-4 w-4" />Specs</TabsTrigger>
            <TabsTrigger value="mechanical"><Zap className="mr-2 h-4 w-4" />Mechanical</TabsTrigger>
            <TabsTrigger value="performance"><GaugeIcon className="mr-2 h-4 w-4" />Performance</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <div className="grid gap-6">
              <Card className="p-6">
                <div className="flex items-start gap-3 mb-4">
                  <Info className="h-6 w-6 text-primary mt-0.5" />
                  <h3 className="text-xl font-semibold">Description</h3>
                </div>
                <p className="text-sm leading-relaxed text-muted-foreground">{data.description || data.general_information}</p>
              </Card>

              <Card className="p-6">
                <div className="flex items-start gap-3 mb-4">
                  <Boxes className="h-6 w-6 text-primary mt-0.5" />
                  <h3 className="text-xl font-semibold">General Information</h3>
                </div>
                <p className="text-sm leading-relaxed text-muted-foreground">{data.general_information}</p>
              </Card>

              <div className="grid md:grid-cols-2 gap-6">
                <Card className="p-5">
                  <div className="flex items-center gap-3 mb-4">
                    <Gauge className="h-6 w-6 text-orange-500" />
                    <h3 className="font-semibold text-lg">Assembly Complexity</h3>
                  </div>
                  <Progress value={complexityValue} className="h-3 mb-3" />
                  <p className="text-sm text-muted-foreground capitalize">{data.assembly_complexity || "N/A"}</p>
                </Card>

                <Card className="p-5">
                  <div className="flex items-center gap-3 mb-4">
                    <DollarSign className="h-6 w-6 text-green-500" />
                    <h3 className="font-semibold text-lg">Estimated Cost</h3>
                  </div>
                  <Progress value={costValue} className="h-3 mb-3" />
                  <p className="text-sm text-muted-foreground">{data.estimated_cost || "N/A"}</p>
                </Card>
              </div>

              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <Wrench className="h-6 w-6 text-blue-500" />
                  <h3 className="text-xl font-semibold">Applications</h3>
                </div>
                <div className="grid gap-3">
                  {(data.applications || []).map((app: string, i: number) => (
                    <div key={i} className="flex items-center gap-3">
                      <div className="w-2 h-2 rounded-full bg-primary" />
                      <p className="text-sm">{app}</p>
                    </div>
                  ))}
                  {(!data.applications || data.applications.length === 0) && (
                    <p className="text-sm text-muted-foreground">No specific applications listed</p>
                  )}
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="specs" className="space-y-6">
            <div className="grid gap-6 md:grid-cols-2">
              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <Ruler className="h-6 w-6 text-blue-500" />
                  <h3 className="text-xl font-semibold">Dimensions</h3>
                </div>
                <div className="space-y-1 text-sm">
                  {renderKeyValuePairs(data.dimensions)}
                  {(!data.dimensions || Object.keys(data.dimensions).length === 0) && (
                    <p className="text-muted-foreground">No dimensions provided</p>
                  )}
                </div>
              </Card>

              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <Hammer className="h-6 w-6 text-amber-600" />
                  <h3 className="text-xl font-semibold">Materials</h3>
                </div>
                <div className="space-y-2">
                  {(data.materials || []).filter(Boolean).map((mat: string, i: number) => (
                    <Badge key={i} variant="outline" className="mr-2">
                      {mat}
                    </Badge>
                  ))}
                  {(!data.materials || data.materials.length === 0) && (
                    <p className="text-sm text-muted-foreground">No materials specified</p>
                  )}
                </div>
              </Card>

              <Card className="p-6 md:col-span-2">
                <div className="flex items-center gap-3 mb-4">
                  <Boxes className="h-6 w-6 text-purple-500" />
                  <h3 className="text-xl font-semibold">Physical Properties</h3>
                </div>
                <div className="space-y-1 text-sm">
                  {renderKeyValuePairs(data.physical_properties)}
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="mechanical" className="space-y-6">
            <Card className="p-6">
              <div className="flex items-center gap-3 mb-4">
                <Zap className="h-6 w-6 text-yellow-500" />
                <h3 className="text-xl font-semibold">Mechanical Properties</h3>
              </div>
              <div className="space-y-1 text-sm">
                {renderKeyValuePairs(data.mechanical_properties)}
                {(!data.mechanical_properties || Object.keys(data.mechanical_properties).length === 0) && (
                  <p className="text-muted-foreground">No mechanical properties specified</p>
                )}
              </div>
            </Card>

            <Card className="p-6">
              <div className="flex items-center gap-3 mb-4">
                <Battery className="h-6 w-6 text-green-500" />
                <h3 className="text-xl font-semibold">Power Requirements</h3>
              </div>
              <p className="text-sm">{data.power_requirements || "N/A (passive component)"}</p>
            </Card>
          </TabsContent>

          <TabsContent value="performance" className="space-y-6">
            <div className="grid gap-6 md:grid-cols-2">
              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <Move className="h-6 w-6 text-indigo-500" />
                  <h3 className="text-xl font-semibold">Motion Characteristics</h3>
                </div>
                <div className="space-y-4 text-sm">
                  <div>
                    <span className="text-muted-foreground">Degree of Freedom:</span>
                    <span className="ml-3 font-medium">{data.degree_of_freedom || "N/A"}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Speed:</span>
                    <span className="ml-3 font-medium">{data.speed || "N/A"}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Range of Motion:</span>
                    <span className="ml-3 font-medium">{data.range_of_motion || "N/A"}</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">Force/Torque Output:</span>
                    <span className="ml-3 font-medium">{data.force_output || "N/A"}</span>
                  </div>
                </div>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </Card>
    </div>
  );
};

export default memo(ComponentResult);